In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/processed/netflix_cleaned.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [2]:
# Create empty columns
df["duration_minutes"] = np.nan
df["seasons"] = np.nan

# If type = Movie → extract minutes
movie_mask = df["type"] == "Movie"
df.loc[movie_mask, "duration_minutes"] = (
    df.loc[movie_mask, "duration"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(float)
)

# If type = TV Show → extract seasons
tv_mask = df["type"] == "TV Show"
df.loc[tv_mask, "seasons"] = (
    df.loc[tv_mask, "duration"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(float)
)

df[["type", "duration", "duration_minutes", "seasons"]].head(20)

       type   duration  duration_minutes  seasons
0     Movie     90 min               NaN      NaN
1   TV Show  2 Seasons               NaN      NaN
2   TV Show   1 Season               NaN      NaN
3   TV Show   1 Season               NaN      NaN
4   TV Show  2 Seasons               NaN      NaN
5   TV Show   1 Season               NaN      NaN
6     Movie     91 min               NaN      NaN
7     Movie    125 min               NaN      NaN
8   TV Show  9 Seasons               NaN      NaN
9     Movie    104 min               NaN      NaN
10  TV Show   1 Season               NaN      NaN
11  TV Show   1 Season               NaN      NaN
12    Movie    127 min               NaN      NaN
13    Movie     91 min               NaN      NaN
14  TV Show   1 Season               NaN      NaN
15  TV Show  4 Seasons               NaN      NaN
16    Movie     67 min               NaN      NaN
17  TV Show  2 Seasons               NaN      NaN
18    Movie     94 min               NaN      NaN
19  TV Show   1 Season               NaN      NaN

In [3]:
df[["duration_minutes", "seasons"]].isna().sum()

duration_minutes    8807
seasons             8807
dtype: int64

In [4]:
import pandas as pd

INPUT_PATH = "../data/processed/netflix_processed.csv"
OUTPUT_PATH = "../data/processed/netflix_processed.csv"

df = pd.read_csv(INPUT_PATH)

# Movies → minutes
df["duration_minutes"] = None
movie_mask = df["type"] == "Movie"
df.loc[movie_mask, "duration_minutes"] = (
    df.loc[movie_mask, "duration"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(float)
)

# TV Shows → seasons
df["seasons"] = None
tv_mask = df["type"] == "TV Show"
df.loc[tv_mask, "seasons"] = (
    df.loc[tv_mask, "duration"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(float)
)

df.to_csv(OUTPUT_PATH, index=False)

print("✅ Saved successfully!")
print(df.columns)

✅ Saved successfully!
Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'year_added', 'month_added', 'genre_count', 'country_count',
       'duration_value', 'duration_type', 'duration_minutes', 'seasons'],
      dtype='object')

In [5]:
df.to_csv("../data/processed/netflix_final.csv", index=False)
print("✅ Saved: data/processed/netflix_final.csv")

✅ Saved: data/processed/netflix_final.csv

In [6]:
import pandas as pd

# Load cleaned dataset
df = pd.read_csv("../data/processed/netflix_cleaned.csv")

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [7]:
# Distribution of Content Type
type_counts = df["type"].value_counts()
type_counts

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

# 📊 Milestone 2 – Exploratory Data Analysis (EDA)

---

## 🔵 Univariate Analysis

In [8]:
# Distribution of Content Type
type_counts = df["type"].value_counts()
type_counts

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [9]:
import plotly.express as px

In [10]:
type_counts_df = df["type"].value_counts().reset_index()
type_counts_df.columns = ["Type", "Count"]

fig = px.bar(
    type_counts_df,
    x="Type",
    y="Count",
    text="Count",
    title="Distribution of Movies vs TV Shows"
)

fig.show()

In [11]:
rating_counts_df = df["rating"].value_counts().reset_index()
rating_counts_df.columns = ["Rating", "Count"]

fig = px.bar(
    rating_counts_df,
    x="Rating",
    y="Count",
    text="Count",
    title="Distribution of Ratings"
)

fig.show()

In [12]:
year_counts_df = df["release_year"].value_counts().sort_index().reset_index()
year_counts_df.columns = ["Year", "Count"]

fig = px.line(
    year_counts_df,
    x="Year",
    y="Count",
    markers=True,
    title="Content Release Trend Over Years"
)

fig.show()

COUNTRY DISTRIBUTION

In [18]:
import plotly.express as px

country_counts = df["country"].value_counts().head(10).reset_index()
country_counts.columns = ["Country", "Count"]

fig = px.bar(
    country_counts,
    x="Country",
    y="Count",
    text="Count",
    title="Top 10 Countries by Number of Titles"
)

fig.show()

---

## 🟠 Bivariate Analysis

In [13]:
type_rating = pd.crosstab(df["type"], df["rating"])
type_rating

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
type,,,,,,,,,,,,,,,,,
Movie,1,1,1,41,3,75,287,490,797,1427,126,2062,540,131,139,5,3
TV Show,0,0,0,0,0,5,0,0,2,733,94,1145,323,176,195,1,0

1️⃣ Type vs Rating

In [14]:
fig = px.imshow(
    type_rating,
    text_auto=True,
    aspect="auto",
    title="Type vs Rating Relationship"
)

fig.show()

### Insight:

Movies have a wider variety of rating categories.
TV Shows are mostly concentrated in TV-MA and TV-14 ratings,
indicating strong focus on mature and teen audiences.

In [15]:
type_year = df.groupby(["release_year", "type"]).size().reset_index(name="Count")

fig = px.line(
    type_year,
    x="release_year",
    y="Count",
    color="type",
    title="Movies vs TV Shows Over Time"
)

fig.show()

### Insight:

Both Movies and TV Shows increased significantly after 2015.
However, TV Shows show faster growth in recent years.

3️⃣ Duration vs Type

In [16]:
# Extract numeric part from duration column
df["duration_numeric"] = df["duration"].str.extract(r"(\d+)").astype(float)

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_numeric
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90.0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1.0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1.0
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2.0

In [17]:
df_movies = df[df["type"] == "Movie"]

fig = px.histogram(
    df_movies,
    x="duration_numeric",
    nbins=30,
    title="Distribution of Movie Duration"
)

fig.show()

---

# 📊 Overall Findings from EDA

- The dataset contains more Movies than TV Shows.
- Most content is rated TV-MA and TV-14, targeting mature audiences.
- Content production significantly increased after 2015.
- The United States contributes the highest number of titles.
- Most movies have durations between 90–120 minutes.
- TV Shows generally have 1–3 seasons.
- Netflix content shows strong growth in recent years.