In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
df = pd.read_csv("../data/Cleaned_netflix_titles.csv")

df.head()

,Unnamed: 0,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,primary_genre
0,0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not-Mentioned,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9,Documentaries
1,1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,International TV Shows
2,2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,Crime TV Shows
3,3,s4,TV Show,Jailbirds New Orleans,Unknown,Not-Mentioned,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,9,Docuseries
4,4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,9,International TV Shows

In [4]:
df['duration_num'] = df['duration'].str.extract(r'(\d+)').astype(int)

df[['duration', 'duration_num']].head()

    duration  duration_num
0     90 min            90
1  2 Seasons             2
2   1 Season             1
3   1 Season             1
4  2 Seasons             2

In [5]:
features = df[['release_year', 'duration_num', 'rating', 'primary_genre', 'country', 'type']].copy()

features.head()

,release_year,duration_num,rating,primary_genre,country,type
0,2020,90,PG-13,Documentaries,United States,Movie
1,2021,2,TV-MA,International TV Shows,South Africa,TV Show
2,2021,1,TV-MA,Crime TV Shows,Unknown,TV Show
3,2021,1,TV-MA,Docuseries,Unknown,TV Show
4,2021,2,TV-MA,International TV Shows,India,TV Show

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

features['rating_encoded'] = le.fit_transform(features['rating'])
features['genre_encoded'] = le.fit_transform(features['primary_genre'])
features['country_encoded'] = le.fit_transform(features['country'])
features['type_encoded'] = le.fit_transform(features['type'])

features.head()

,release_year,duration_num,rating,primary_genre,country,type,rating_encoded,genre_encoded,country_encoded,type_encoded
0,2020,90,PG-13,Documentaries,United States,Movie,4,10,79,0
1,2021,2,TV-MA,International TV Shows,South Africa,TV Show,8,16,66,1
2,2021,1,TV-MA,Crime TV Shows,Unknown,TV Show,8,8,80,1
3,2021,1,TV-MA,Docuseries,Unknown,TV Show,8,11,80,1
4,2021,2,TV-MA,International TV Shows,India,TV Show,8,16,29,1

In [7]:
X = features[['release_year', 'duration_num', 'rating_encoded', 'genre_encoded', 'country_encoded']]

y = features['type_encoded']

X.head()

   release_year  duration_num  rating_encoded  genre_encoded  country_encoded
0          2020            90               4             10               79
1          2021             2               8             16               66
2          2021             1               8              8               80
3          2021             1               8             11               80
4          2021             2               8             16               29

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

Training samples: (7035, 5)
Testing samples: (1759, 5)

In [9]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42)

model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [10]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

Model Accuracy: 0.9977259806708357

The high accuracy is largely driven by the duration feature because movies are represented in minutes while TV shows are represented in seasons, making them easily distinguishable.

In [11]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[1217    3]
 [   1  538]]

The confusion matrix shows that the model correctly classified most of the samples, with only a few misclassifications between movies and TV shows. The model achieved approximately 99.7% accuracy, mainly because the duration feature strongly distinguishes movies from TV shows.

In [12]:
cluster_features = features[['release_year', 'duration_num', 'rating_encoded', 'genre_encoded']]

cluster_features.head()

   release_year  duration_num  rating_encoded  genre_encoded
0          2020            90               4             10
1          2021             2               8             16
2          2021             1               8              8
3          2021             1               8             11
4          2021             2               8             16

In [13]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=4, random_state=42)

features['cluster'] = kmeans.fit_predict(cluster_features)

features[['release_year','duration_num','cluster']].head()

   release_year  duration_num  cluster
0          2020            90        1
1          2021             2        0
2          2021             1        0
3          2021             1        0
4          2021             2        0

I applied K-Means clustering to group similar Netflix content based on release year, duration, rating, and genre. This helps identify natural groupings within the content library.

In [14]:
fig = px.scatter(
    features,
    x="release_year",
    y="duration_num",
    color="cluster",
    title="Netflix Content Clusters",
    hover_data=["primary_genre", "rating"]
)

fig.show()

In [15]:
features.groupby('cluster')[['release_year','duration_num']].mean()

         release_year  duration_num
cluster
0         2016.573456      2.955287
1         2013.790471     99.705468
2         2009.021997    139.438240
3         2014.927273     66.747273

Using K-Means clustering, Netflix content was grouped into four clusters based on release year, duration, genre, and rating. The clusters reveal patterns such as short-duration TV shows, medium-length movies, long movies, and older content groups.